#!/bin/bash


get_brightness_percentage() {
    echo $(( $(brightnessctl get) * 100 / $(brightnessctl max) ))
}

brightness_icon="󰃠"

# Get the current brightness percentage
current_brightness_percentage=$(get_brightness_percentage)

# Output the brightness percentage
eww update current-brightness="$brightness_icon  $current_brightness_percentage%"

eww update brightness-value=$(get_brightness_percentage)