#!/bin/bash



get_current_volume() {
    pactl get-sink-volume @DEFAULT_SINK@ | grep -o '[0-9]*%' | head -n 1
}

get_current_status() {
    pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}'
}

current_volume=$(get_current_volume)
mute_status=$(get_current_status)

# Check if an argument is provided
if [ "$1" == "increase" ]; then
    wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
elif [ "$1" == "decrease" ]; then
    wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%-
elif [ "$1" == "togglemute" ]; then
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
else
    echo "Usage: $0 [increase|decrease|togglemute]"
    exit 1
fi

if eww active-windows | grep "volume-widget"; then
    # If it's open, refresh the widget
    /home/$USER/.config/eww/scripts/volume

    while [ "$current_volume" != "$(get_current_volume)" ]; do
        sleep 5
        current_volume=$(get_current_volume)
    done

    eww close volume-widget
    
else
    # If it's not open, open the widget
    /home/$USER/.config/eww/scripts/volume
    eww open volume-widget
fi




