#!/bin/bash

# Define icons
unmuted_icon=""
muted_icon=""

# Get the current mute status and volume percentage
mute_status=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -o '[0-9]*%' | head -n 1)

# Check if the volume is muted
if [ "$mute_status" == "no" ]; then
    echo "$unmuted_icon  $volume"
else
    echo "$muted_icon"
fi
