#!/bin/bash

icons=("" "睊")

# Check WiFi status using nmcli
wifi_status=$(nmcli -t -f WIFI g)

if [ "$wifi_status" = "enabled" ]; then
    # Get the current SSID if WiFi is enabled
    wifi_ssid=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d':' -f2)
    if [ -n "$wifi_ssid" ]; then
        echo "${icons[0]}   $wifi_ssid"
    else
        echo "${icons[1]}"
    fi
else
    echo "${icons[1]}"
fi
